name: template-ts-semantic-release

on:
  push:
    branches: [$default-branch]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  NODE_VERSION: 22.17.0

jobs:
  integration-test:
    name: Run integration tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: integration_test
          MYSQL_PASSWORD: integration_test
          MYSQL_DATABASE: integration_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Setup Node and install dependencies
        uses: ./.github/actions
        with:
          node_version: ${{ env.NODE_VERSION }}

      - run: npm run test:integration:ci

  type-check:
    name: Typescript build check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Setup Node and install dependencies
        uses: ./.github/actions
        with:
          node_version: ${{ env.NODE_VERSION }}

      - run: npm run build:check

  prettier-check:
    name: Prettier format check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Setup Node and install dependencies
        uses: ./.github/actions
        with:
          node_version: ${{ env.NODE_VERSION }}

      - run: npm run format:check

  lint:
    name: Lint check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Setup Node and install dependencies
        uses: ./.github/actions
        with:
          node_version: ${{ env.NODE_VERSION }}

      - run: npm run lint

  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Setup Node and install dependencies
        uses: ./.github/actions
        with:
          node_version: ${{ env.NODE_VERSION }}

      - run: npm test

