name: Deploy

on:
  workflow_dispatch:
    inputs:
      staging_envs:
        description: 'Select staging environment'
        required: false
        type: choice
        options:
          - '--'
          - se
          - fi
          - 'no'
          - '*'
      production_envs:
        description: 'Select production environment'
        required: false
        type: choice
        options:
          - '--'
          - se
          - fi
          - 'no'
          - '*'
      tag:
        description: 'Specify image tag'
        required: false
        type: string

jobs:
  deploy:
    uses: Advisa/gha-workflow-templates/.github/workflows/deploy.yml@main
    with:
      staging_envs: ${{ github.event.inputs.staging_envs }}
      production_envs: ${{ github.event.inputs.production_envs }}
      tag: ${{ github.event.inputs.tag }}
    secrets:
      AWS_ECR_DEPLOYMENT_ROLE: ${{ secrets.AWS_ECR_DEPLOYMENT_ROLE }}
